### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by divyamsolanki9** [blakebjorn/opennodes#1]
File - crawler.py

`fname = f"visitations_{current_date.strftime('%Y-%m-%d')}.gz"`

Error - Invalid Syntax

**Comment by blakebjorn** [comment]
Python 3.6+

If you don't have 3.6 you can replace all f-strings with a <=3.5 syntax, e.g. `"visitations_" + current_date.strftime('%Y-%m-%d') + ".gz"`
